# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2025 Buo-ren Lin (OSSII) <buoren@ossii.com.tw>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: project-name
services:
  # Environment for developing and building the product
  dev-environment:
    profiles:
      - dev
    container_name: project-name-dev
    hostname: project-name-dev
    image: rockylinux:8
    volumes:
      - type: bind
        source: ./
        target: /project
    environment:
      # Set local timezone to UTC+8
      - TZ=CST-8
    init: true
    command: sleep infinity

  # Environment for testing the product
  test-environment:
    profiles:
      - test
    container_name: project-name-test
    hostname: project-name-test
    image: rockylinux:8
    volumes:
      - type: bind
        source: ./
        target: /project
    environment:
      # Set local timezone to UTC+8
      - TZ=CST-8
    init: true
    command: sleep infinity
