# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2025 Buo-ren Lin (OSSII) <buoren@ossii.com.tw>
# SPDX-License-Identifier: AGPL-3.0-or-later
name: odfweb-apache
volumes:
  odfweb:
  db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      # The password for the "root" user of the database
      - MYSQL_ROOT_PASSWORD=__REDACTED__
      # The password for the service user of the database
      - MYSQL_PASSWORD=__REDACTED__
      # The name of the database
      - MYSQL_DATABASE=odfweb
      # The name of the service user of the database
      - MYSQL_USER=odfweb

  app:
    image: odfweb:4
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - odfweb:/var/www/html
    environment:
      # The password for the service user of the database
      - MYSQL_PASSWORD=__REDACTED__
      # The name of the database
      - MYSQL_DATABASE=odfweb
      # The name of the service user of the database
      - MYSQL_USER=odfweb
      # The host address of the database
      - MYSQL_HOST=db
