# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification â€“ Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2025 Buo-ren Lin (OSSII) <buoren.lin@ossii.com.tw>
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "README.md",
    "**/README.md",
    "README.*.md",
    "**/README.*.md"
]
SPDX-FileCopyrightText = '2025 Buo-ren Lin (OSSII) <buoren.lin@ossii.com.tw>'
SPDX-License-Identifier = 'MIT'
